import './chartfunctions/_create_bar_chart'
import './chartfunctions/_create_line_chart'
import './chartfunctions/_create_polararea_chart'
// import './chartfunctions/_create_polararea_chart_claims'
import './chartfunctions/_create_area_chart'
import './chartfunctions/_create_stacked_area_chart'
import './chartfunctions/_create_doghnut_chart'
